package mybatis.mapper;

import java.util.List;
import mybatis.model.Speciality;

public interface SpecialityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPECIALITY
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPECIALITY
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    int insert(Speciality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPECIALITY
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    Speciality selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPECIALITY
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    List<Speciality> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPECIALITY
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    int updateByPrimaryKey(Speciality record);
}