package mybatis.mapper;

import java.util.List;
import mybatis.model.Subject;
import org.mybatis.cdi.Mapper;

import javax.transaction.Transactional;

@Mapper
public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    Subject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    List<Subject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    @Transactional
    int updateByPrimaryKey(Subject record);
}