package mybatis.model;

public class Speciality {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPECIALITY.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPECIALITY.LENGTH
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPECIALITY.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPECIALITY.ID
     *
     * @return the value of PUBLIC.SPECIALITY.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPECIALITY.ID
     *
     * @param id the value for PUBLIC.SPECIALITY.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPECIALITY.LENGTH
     *
     * @return the value of PUBLIC.SPECIALITY.LENGTH
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPECIALITY.LENGTH
     *
     * @param length the value for PUBLIC.SPECIALITY.LENGTH
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPECIALITY.NAME
     *
     * @return the value of PUBLIC.SPECIALITY.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPECIALITY.NAME
     *
     * @param name the value for PUBLIC.SPECIALITY.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}