package mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.EMAIL
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.STUDENT_GROUP
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private Integer studentGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.YEAR
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.SPECIALITY_ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private Long specialityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.EMAIL
     *
     * @return the value of PUBLIC.STUDENT.EMAIL
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.EMAIL
     *
     * @param email the value for PUBLIC.STUDENT.EMAIL
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.STUDENT_GROUP
     *
     * @return the value of PUBLIC.STUDENT.STUDENT_GROUP
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public Integer getStudentGroup() {
        return studentGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.STUDENT_GROUP
     *
     * @param studentGroup the value for PUBLIC.STUDENT.STUDENT_GROUP
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setStudentGroup(Integer studentGroup) {
        this.studentGroup = studentGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @return the value of PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @param surname the value for PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.YEAR
     *
     * @return the value of PUBLIC.STUDENT.YEAR
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.YEAR
     *
     * @param year the value for PUBLIC.STUDENT.YEAR
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.SPECIALITY_ID
     *
     * @return the value of PUBLIC.STUDENT.SPECIALITY_ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public Long getSpecialityId() {
        return specialityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.SPECIALITY_ID
     *
     * @param specialityId the value for PUBLIC.STUDENT.SPECIALITY_ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setSpecialityId(Long specialityId) {
        this.specialityId = specialityId;
    }
}