package mybatis.model;

public class Subject {
    public Subject() {
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.CREDIT_AMOUNT
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private Integer creditAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.DESCRIPTION
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.LECTURER
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private String lecturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.ID
     *
     * @return the value of PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.ID
     *
     * @param id the value for PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.CREDIT_AMOUNT
     *
     * @return the value of PUBLIC.SUBJECT.CREDIT_AMOUNT
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public Integer getCreditAmount() {
        return creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.CREDIT_AMOUNT
     *
     * @param creditAmount the value for PUBLIC.SUBJECT.CREDIT_AMOUNT
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setCreditAmount(Integer creditAmount) {
        this.creditAmount = creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.DESCRIPTION
     *
     * @return the value of PUBLIC.SUBJECT.DESCRIPTION
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.DESCRIPTION
     *
     * @param description the value for PUBLIC.SUBJECT.DESCRIPTION
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.LECTURER
     *
     * @return the value of PUBLIC.SUBJECT.LECTURER
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public String getLecturer() {
        return lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.LECTURER
     *
     * @param lecturer the value for PUBLIC.SUBJECT.LECTURER
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setLecturer(String lecturer) {
        this.lecturer = lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @return the value of PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @param name the value for PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Mon Apr 04 21:27:55 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}